import React,{useEffect,useMemo,useState} from 'react';
import {createRoot} from 'react-dom/client';
import {supabase,PRODUCT_BUCKET} from './supabase';
import './admin.css';

const empty={name:'',price:'',salePrice:'',category:'Casual',sizes:'S, M, L',colors:'',fabric:'',stock:'',description:'',image_url:''};
const fallback=[
{id:1,name:'Burgundy Grace 2-Piece',price:3290,sale_price:2890,category:'Casual',sizes:['S','M','L','XL'],colors:['Burgundy','Ivory'],fabric:'Premium lawn',stock:7,image_url:''},
{id:2,name:'Ivory Bloom 3-Piece',price:4290,sale_price:null,category:'Casual',sizes:['S','M','L'],colors:['Ivory','Rose'],fabric:'Lawn & voile',stock:11,image_url:''}
];
const toForm=p=>({...empty,...p,salePrice:p.sale_price??'',image_url:p.image_url||'',sizes:Array.isArray(p.sizes)?p.sizes.join(', '):p.sizes||'',colors:Array.isArray(p.colors)?p.colors.join(', '):p.colors||''});
function App(){
 const [products,setProducts]=useState([]),[form,setForm]=useState(empty),[editing,setEditing]=useState(null),[busy,setBusy]=useState(true),[message,setMessage]=useState('');
 const [wa,setWa]=useState(localStorage.getItem('noor_wa_number')||'923262665203');
 const notify=m=>{setMessage(m);setTimeout(()=>setMessage(''),5000)};
 const load=async()=>{setBusy(true);const {data,error}=await supabase.from('products').select('*').order('id',{ascending:false});if(error){setProducts(fallback);notify('Database read failed: '+error.message)}else setProducts(data||[]);setBusy(false)};
 useEffect(()=>{load()},[]);
 const save=async e=>{e.preventDefault();setBusy(true);setMessage('Saving product…');
  const p={name:form.name.trim(),price:Number(form.price)||0,sale_price:form.salePrice===''?null:Number(form.salePrice),category:form.category,sizes:form.sizes.split(',').map(x=>x.trim()).filter(Boolean),colors:form.colors.split(',').map(x=>x.trim()).filter(Boolean),fabric:form.fabric.trim(),stock:Number(form.stock)||0,description:form.description.trim(),image_url:form.image_url};
  try{const result=editing?await supabase.from('products').update(p).eq('id',editing).select().single():await supabase.from('products').insert(p).select().single();
   if(result.error){console.error(result.error);notify('SAVE FAILED: '+result.error.message)}else{notify(editing?'Product updated ✓':'Product added ✓');setEditing(null);setForm(empty);await load()}
  }catch(err){console.error(err);notify('SAVE FAILED: '+(err?.message||String(err)))}finally{setBusy(false)}
 };
 const remove=async id=>{if(!confirm('Delete this product?'))return;setBusy(true);const {error}=await supabase.from('products').delete().eq('id',id);if(error)notify('DELETE FAILED: '+error.message);else{setProducts(a=>a.filter(x=>x.id!==id));notify('Product deleted ✓')}setBusy(false)};
 const upload=async e=>{const file=e.target.files?.[0];if(!file)return;setBusy(true);setMessage('Uploading image…');const ext=file.name.split('.').pop()?.toLowerCase()||'jpg';const path=`${Date.now()}-${Math.random().toString(36).slice(2)}.${ext}`;try{const {error}=await supabase.storage.from(PRODUCT_BUCKET).upload(path,file,{upsert:false,contentType:file.type});if(error)throw error;const {data}=supabase.storage.from(PRODUCT_BUCKET).getPublicUrl(path);setForm(x=>({...x,image_url:data.publicUrl}));notify('Image uploaded ✓')}catch(err){notify('IMAGE UPLOAD FAILED: '+(err?.message||String(err)))}finally{setBusy(false)}};
 const stats=useMemo(()=>({total:products.length,stock:products.reduce((a,x)=>a+Number(x.stock||0),0)}),[products]);
 const edit=p=>{setEditing(p.id);setForm(toForm(p));window.scrollTo({top:0,behavior:'smooth'})};
 const saveWa=()=>{localStorage.setItem('noor_wa_number',wa);notify('WhatsApp number saved ✓')};
 return <div className="admin"><header><div><span className="eyebrow">NOOR / CONTROL</span><h1>Store Manager</h1><p>Manage your live catalogue without touching code.</p></div><a href="/" className="store">View Store ↗</a></header>
 {message&&<div className="notice">{message}</div>}
 <section className="stats"><div><b>{stats.total}</b><span>Products</span></div><div><b>{stats.stock}</b><span>Units in stock</span></div></section>
 <section className="panel"><div className="panelhead"><div><span className="eyebrow">PRODUCT</span><h2>{editing?'Edit product':'Add a product'}</h2></div>{editing&&<button className="ghost" type="button" onClick={()=>{setEditing(null);setForm(empty)}}>Cancel</button>}</div>
 <form onSubmit={save} className="form"><label>Product name<input required value={form.name} onChange={e=>setForm({...form,name:e.target.value})}/></label><div className="two"><label>Price (PKR)<input required type="number" value={form.price} onChange={e=>setForm({...form,price:e.target.value})}/></label><label>Sale price<input type="number" value={form.salePrice} onChange={e=>setForm({...form,salePrice:e.target.value})}/></label></div><div className="two"><label>Category<select value={form.category} onChange={e=>setForm({...form,category:e.target.value})}>{['Casual','Semi-Formal','Party & Wedding','Co-ords','2-Piece','3-Piece','Sale'].map(x=><option key={x}>{x}</option>)}</select></label><label>Stock<input type="number" value={form.stock} onChange={e=>setForm({...form,stock:e.target.value})}/></label></div><div className="two"><label>Sizes<input value={form.sizes} placeholder="S, M, L, XL" onChange={e=>setForm({...form,sizes:e.target.value})}/></label><label>Colors<input value={form.colors} placeholder="Burgundy, Ivory" onChange={e=>setForm({...form,colors:e.target.value})}/></label></div><label>Fabric<input value={form.fabric} onChange={e=>setForm({...form,fabric:e.target.value})}/></label><label>Description<textarea rows="3" value={form.description} onChange={e=>setForm({...form,description:e.target.value})}/></label><label>Product image<input type="file" accept="image/*" onChange={upload}/></label>{form.image_url&&<img className="preview" src={form.image_url} alt="Product preview"/>}<button className="primary" disabled={busy}>{busy?'Working…':editing?'Update product':'Add product'}</button></form></section>
 <section className="panel"><div className="panelhead"><div><span className="eyebrow">LIVE CATALOG</span><h2>Your products</h2></div></div>{busy&&!products.length?<p>Loading catalogue…</p>:<div className="list">{products.map(p=><article key={p.id}><div className="thumb">{p.image_url?<img src={p.image_url} alt=""/>:<span>NOOR</span>}</div><div className="meta"><strong>{p.name}</strong><small>{p.category} · PKR {Number(p.sale_price||p.price).toLocaleString()} · Stock {p.stock??0}</small></div><button className="ghost" type="button" onClick={()=>edit(p)}>Edit</button><button className="danger" type="button" onClick={()=>remove(p.id)}>Delete</button></article>)}</div>}</section>
 <section className="panel"><div className="panelhead"><div><span className="eyebrow">SETTINGS</span><h2>WhatsApp ordering</h2></div></div><label>WhatsApp number<input value={wa} onChange={e=>setWa(e.target.value.replace(/\D/g,''))}/></label><p className="hint">Country code without +. Example: 923001234567</p><button className="primary" type="button" onClick={saveWa}>Save WhatsApp number</button></section><footer>Noor Store Manager · Supabase-powered catalogue</footer></div>}
createRoot(document.getElementById('root')).render(<App/>);
