import React,{useEffect,useMemo,useState} from 'react';
import {createRoot} from 'react-dom/client';
import {supabase,PRODUCT_BUCKET} from './supabase';
import './admin.css';

const empty={name:'',price:'',salePrice:'',category:'Casual',sizes:'S, M, L',colors:'',description:'',image_url:''};
const fallback=[];
const toForm=p=>({...empty,...p,salePrice:p.sale_price??'',image_url:p.image_URL||'',sizes:p.sizes||'',colors:p.colors||''});
const timeout=ms=>new Promise((_,reject)=>setTimeout(()=>reject(new Error('Request timed out. Please check the Supabase database policies.')),ms));
function App(){
 const [products,setProducts]=useState([]),[form,setForm]=useState(empty),[editing,setEditing]=useState(null),[busy,setBusy]=useState(true),[message,setMessage]=useState('');
 const [wa,setWa]=useState(localStorage.getItem('noor_wa_number')||'923262665203');
 const notify=m=>{setMessage(m);setTimeout(()=>setMessage(''),8000)};
 const load=async()=>{setBusy(true);try{const r=await Promise.race([supabase.from('products').select('*').order('id',{ascending:false}),timeout(10000)]);if(r.error)throw r.error;setProducts(r.data||[])}catch(error){console.error(error);setProducts(fallback);notify('CATALOG LOAD FAILED: '+error.message)}finally{setBusy(false)}};
 useEffect(()=>{load()},[]);
 const save=async e=>{e.preventDefault();if(!form.name.trim()){notify('Please enter a product name.');return}setBusy(true);setMessage('Saving product…');
  const p={name:form.name.trim(),price:Number(form.price)||0,sale_price:form.salePrice===''?null:Number(form.salePrice),category:form.category,sizes:form.sizes.trim(),colors:form.colors.trim(),description:form.description.trim(),image_URL:form.image_url||null};
  try{let r;if(editing){r=await Promise.race([supabase.from('products').update(p).eq('id',editing),timeout(15000)])}else{r=await Promise.race([supabase.from('products').insert(p),timeout(15000)])}if(r.error)throw r.error;notify(editing?'Product updated ✓':'Product added ✓');setEditing(null);setForm(empty);await load()}catch(err){console.error(err);notify('SAVE FAILED: '+(err?.message||String(err)))}finally{setBusy(false)}};
 const remove=async id=>{if(!confirm('Delete this product?'))return;setBusy(true);try{const r=await Promise.race([supabase.from('products').delete().eq('id',id),timeout(15000)]);if(r.error)throw r.error;notify('Product deleted ✓');await load()}catch(err){notify('DELETE FAILED: '+err.message)}finally{setBusy(false)}};
 const upload=async e=>{const file=e.target.files?.[0];if(!file)return;setBusy(true);setMessage('Uploading image…');const ext=file.name.split('.').pop()?.toLowerCase()||'jpg';const path=`${Date.now()}-${Math.random().toString(36).slice(2)}.${ext}`;try{const r=await Promise.race([supabase.storage.from(PRODUCT_BUCKET).upload(path,file,{upsert:false,contentType:file.type}),timeout(20000)]);if(r.error)throw r.error;const {data}=supabase.storage.from(PRODUCT_BUCKET).getPublicUrl(path);setForm(x=>({...x,image_url:data.publicUrl}));notify('Image uploaded ✓')}catch(err){notify('IMAGE UPLOAD FAILED: '+(err?.message||String(err)))}finally{setBusy(false)}};
 const stats=useMemo(()=>({total:products.length}),[products]);
 const edit=p=>{setEditing(p.id);setForm(toForm(p));window.scrollTo({top:0,behavior:'smooth'})};
 const saveWa=()=>{localStorage.setItem('noor_wa_number',wa);notify('WhatsApp number saved ✓')};
 return <div className="admin"><header><div><span className="eyebrow">NOOR / CONTROL</span><h1>Store Manager</h1><p>Manage your live catalogue without touching code.</p></div><a href="/" className="store">View Store ↗</a></header>
 {message&&<div className="notice">{message}</div>}
 <section className="stats"><div><b>{stats.total}</b><span>Products</span></div></section>
 <section className="panel"><div className="panelhead"><div><span className="eyebrow">PRODUCT</span><h2>{editing?'Edit product':'Add a product'}</h2></div>{editing&&<button className="ghost" type="button" onClick={()=>{setEditing(null);setForm(empty)}}>Cancel</button>}</div>
 <form onSubmit={save} className="form"><label>Product name<input required value={form.name} onChange={e=>setForm({...form,name:e.target.value})}/></label><div className="two"><label>Price (PKR)<input required type="number" value={form.price} onChange={e=>setForm({...form,price:e.target.value})}/></label><label>Sale price<input type="number" value={form.salePrice} onChange={e=>setForm({...form,salePrice:e.target.value})}/></label></div><label>Category<select value={form.category} onChange={e=>setForm({...form,category:e.target.value})}>{['Casual','Semi-Formal','Party & Wedding','Co-ords','2-Piece','3-Piece','Sale'].map(x=><option key={x}>{x}</option>)}</select></label><div className="two"><label>Sizes<input value={form.sizes} placeholder="S, M, L, XL" onChange={e=>setForm({...form,sizes:e.target.value})}/></label><label>Colors<input value={form.colors} placeholder="Burgundy, Ivory" onChange={e=>setForm({...form,colors:e.target.value})}/></label></div><label>Description<textarea rows="3" value={form.description} onChange={e=>setForm({...form,description:e.target.value})}/></label><label>Product image<input type="file" accept="image/*" onChange={upload}/></label>{form.image_url&&<img className="preview" src={form.image_url} alt="Product preview"/>}<button className="primary" disabled={busy}>{busy?'Working…':editing?'Update product':'Add product'}</button></form></section>
 <section className="panel"><div className="panelhead"><div><span className="eyebrow">LIVE CATALOG</span><h2>Your products</h2></div></div>{busy&&!products.length?<p>Loading catalogue…</p>:<div className="list">{products.map(p=><article key={p.id}><div className="thumb">{p.image_URL?<img src={p.image_URL} alt=""/>:<span>NOOR</span>}</div><div className="meta"><strong>{p.name}</strong><small>{p.category} · PKR {Number(p.sale_price||p.price).toLocaleString()}</small></div><button className="ghost" type="button" onClick={()=>edit(p)}>Edit</button><button className="danger" type="button" onClick={()=>remove(p.id)}>Delete</button></article>)}</div>}</section>
 <section className="panel"><div className="panelhead"><div><span className="eyebrow">SETTINGS</span><h2>WhatsApp ordering</h2></div></div><label>WhatsApp number<input value={wa} onChange={e=>setWa(e.target.value.replace(/\D/g,''))}/></label><p className="hint">Country code without +. Example: 923001234567</p><button className="primary" type="button" onClick={saveWa}>Save WhatsApp number</button></section><footer>Noor Store Manager · Supabase-powered catalogue</footer></div>}
createRoot(document.getElementById('root')).render(<App/>);
