import React,{useEffect,useMemo,useState} from "react";
import {createRoot} from "react-dom/client";
import {ArrowRight,Heart,Minus,Plus,Search,ShoppingBag,MessageCircle,UserRound,X,Check,ChevronDown} from "lucide-react";
import {supabase} from "./supabase";
import "./styles.css";

const WA_NUMBER="923262665203";
const fallbackImage="https://images.unsplash.com/photo-1496747611176-843222e1e57c?auto=format&fit=crop&w=900&q=82";
const money=n=>`PKR ${Number(n||0).toLocaleString("en-PK")}`;
const normalize=p=>({
 id:p.id,name:p.name||"Untitled product",category:p.category||"Casual",style:p.category||"Casual",
 type:p.category==="Co-ords"?"Co-ord":(p.type||"3-Piece"),price:Number(p.price)||0,salePrice:p.sale_price==null?null:Number(p.sale_price),
 sizes:String(p.sizes||"").split(",").map(x=>x.trim()).filter(Boolean),colors:String(p.colors||"").split(",").map(x=>x.trim()).filter(Boolean),
 fabric:"Premium fabric",stock:0,newArrival:true,featured:true,bestseller:true,desc:p.description||"Elegant Pakistani wear, thoughtfully designed for everyday and occasion dressing.",
 images:[p.image_URL||fallbackImage]
});

function App(){
 const [products,setProducts]=useState([]),[loading,setLoading]=useState(true),[error,setError]=useState("");
 const [page,setPage]=useState("home"),[selected,setSelected]=useState(null),[cart,setCart]=useState([]),[wishlist,setWishlist]=useState([]),[search,setSearch]=useState(""),[mobileSearch,setMobileSearch]=useState(false),[toast,setToast]=useState("");
 const [filters,setFilters]=useState({category:"All",sort:"Featured"});
 const notify=t=>{setToast(t);setTimeout(()=>setToast(""),2200)};
 const load=async()=>{setLoading(true);setError("");const r=await supabase.from("products").select("*").order("id",{ascending:false});if(r.error){setError(r.error.message);setProducts([])}else setProducts((r.data||[]).map(normalize));setLoading(false)};
 useEffect(()=>{load()},[]);
 const openProduct=p=>{setSelected(p);setPage("product");window.scrollTo({top:0,behavior:"smooth"})};
 const addToCart=(p,size=p.sizes[1]||p.sizes[0]||"M")=>{setCart(c=>{const f=c.find(x=>x.id===p.id&&x.size===size);return f?c.map(x=>x.id===p.id&&x.size===size?{...x,qty:x.qty+1}:x):[...c,{...p,size,qty:1}]});notify(`${p.name} added to cart`)};
 const toggleWish=p=>{setWishlist(w=>w.includes(p.id)?w.filter(x=>x!==p.id):[...w,p.id]);notify(wishlist.includes(p.id)?"Removed from wishlist":"Saved to wishlist")};
 const filtered=useMemo(()=>{let list=[...products];if(filters.category!=="All")list=list.filter(p=>p.category===filters.category);if(search.trim()){const q=search.toLowerCase();list=list.filter(p=>(p.name+" "+p.category+" "+p.description).toLowerCase().includes(q))}if(filters.sort==="Price: Low to High")list.sort((a,b)=>(a.salePrice||a.price)-(b.salePrice||b.price));if(filters.sort==="Price: High to Low")list.sort((a,b)=>(b.salePrice||b.price)-(a.salePrice||a.price));return list},[products,filters,search]);
 const total=cart.reduce((s,x)=>s+(x.salePrice||x.price)*x.qty,0),delivery=total>=6000?0:(cart.length?250:0);
 const whatsapp=p=>window.open(`https://wa.me/${WA_NUMBER}?text=${encodeURIComponent(p?`Assalam o Alaikum! I'd like to order ${p.name}. Please confirm availability.`:`Assalam o Alaikum! I'd like help with my order.`)}`,"_blank");
 if(page==="product"&&selected)return <><Header {...{page,setPage,cart,search,setSearch,mobileSearch,setMobileSearch}}/><Product p={selected} addToCart={addToCart} toggleWish={toggleWish} wish={wishlist.includes(selected.id)} whatsapp={whatsapp}/><Footer/><FloatWA/></>;
 return <div className="app"><Header {...{page,setPage,cart,search,setSearch,mobileSearch,setMobileSearch}}/>{page==="home"?<Home products={products} loading={loading} error={error} openProduct={openProduct} addToCart={addToCart} toggleWish={toggleWish} wishlist={wishlist} setPage={setPage} setFilters={setFilters}/>:page==="shop"?<Shop list={filtered} loading={loading} error={error} filters={filters} setFilters={setFilters} openProduct={openProduct} addToCart={addToCart} toggleWish={toggleWish} wishlist={wishlist}/>:page==="cart"?<Cart cart={cart} setCart={setCart} total={total} delivery={delivery} setPage={setPage} openProduct={openProduct}/>:<Home products={products} loading={loading} error={error} openProduct={openProduct} addToCart={addToCart} toggleWish={toggleWish} wishlist={wishlist} setPage={setPage} setFilters={setFilters}/>}<Footer/><FloatWA/>{toast&&<div className="toast"><Check size={16}/>{toast}</div>}</div>;
}

function Header({page,setPage,cart,search,setSearch,mobileSearch,setMobileSearch}){return <header className="header"><div className="topbar">Complimentary delivery on orders over PKR 6,000 <span>•</span> Cash on Delivery nationwide</div><div className="nav container"><button className="icon-btn mobile-only" onClick={()=>setMobileSearch(v=>!v)}><Search size={20}/></button><button className="brand" onClick={()=>{setPage("home");window.scrollTo({top:0})}}><span>MISK</span><small>COLLECTIONS</small></button><nav className="desktop-nav">{["New Arrivals","Casual","Semi-Formal","Party & Wedding","Co-ords","Sale"].map(x=><button key={x} onClick={()=>{setPage("shop");setSearch("");setMobileSearch(false)}}>{x}</button>)}</nav><div className="nav-actions"><div className="search desktop-search"><Search size={17}/><input value={search} onChange={e=>{setSearch(e.target.value);setPage("shop")}} placeholder="Search styles..."/></div><button className="icon-btn" onClick={()=>setPage("home")}><UserRound size={20}/></button><button className="icon-btn" onClick={()=>setPage("cart")}><ShoppingBag size={20}/><b className="count">{cart.reduce((s,x)=>s+x.qty,0)}</b></button></div></div>{mobileSearch&&<div className="mobile-search"><Search size={17}/><input autoFocus value={search} onChange={e=>{setSearch(e.target.value);setPage("shop")}} placeholder="Search styles..."/></div>}</header>}

function Home({products,loading,error,openProduct,addToCart,toggleWish,wishlist,setPage,setFilters}){const featured=products.slice(0,8);const go=c=>{setFilters(f=>({...f,category:c}));setPage("shop");window.scrollTo({top:0})};return <main><section className="hero container"><div className="hero-copy"><span className="eyebrow">THE NEW PAKISTANI EDIT</span><h1>Affordable<br/><em>Elegance,</em> Made for You</h1><p>Discover elegant Pakistani women's wear designed for everyday confidence, office style and special occasions.</p><div className="hero-actions"><button className="btn primary" onClick={()=>{setPage("shop");setFilters(f=>({...f,category:"All",sort:"Featured"}))}}>SHOP THE COLLECTION <ArrowRight size={17}/></button><button className="btn ghost" onClick={()=>document.getElementById("categories")?.scrollIntoView({behavior:"smooth"})}>EXPLORE COLLECTION</button></div></div><div className="hero-image"><img src={featured[0]?.images[0]||fallbackImage} alt="Noor collection"/></div></section><section className="section container" id="categories"><div className="section-head"><span className="eyebrow">SHOP THE EDIT</span><h2>Shop by Category</h2><p>Find the pieces that fit your day, your plans and your personal style.</p></div><div className="category-grid">{["Casual","Semi-Formal","Party & Wedding","Co-ords"].map((x,i)=><button className="category-card" key={x} onClick={()=>go(x)}><span>0{i+1}</span><strong>{x}</strong><ArrowRight size={18}/></button>)}</div></section><section className="section soft"><div className="container"><div className="section-head center"><span className="eyebrow">LIVE CATALOGUE</span><h2>Our Collection</h2><p>Products added or updated in Store Manager appear here automatically.</p></div>{loading?<p className="center">Loading live catalogue…</p>:error?<p className="center">Could not load catalogue: {error}</p>:!products.length?<div className="empty"><ShoppingBag size={40}/><h3>No products yet</h3><p>Add products from Store Manager and they will appear here.</p></div>:<ProductGrid list={featured} {...{openProduct,addToCart,toggleWish,wishlist}}/>}</div></section></main>}

function Shop({list,loading,error,filters,setFilters,openProduct,addToCart,toggleWish,wishlist}){return <main><section className="shop-hero"><div className="container"><span className="eyebrow">THE COLLECTION</span><h1>Shop the Edit</h1><p>Live products from the Noor Store Manager.</p></div></section><div className="container shop-wrap"><div className="shop-toolbar"><span>{list.length} styles</span><select value={filters.sort} onChange={e=>setFilters(f=>({...f,sort:e.target.value}))}><option>Featured</option><option>Price: Low to High</option><option>Price: High to Low</option></select></div><div className="filter-group"><h4>Category</h4>{["All","Casual","Semi-Formal","Party & Wedding","Co-ords"].map(v=><button className={v===filters.category?"selected":""} key={v} onClick={()=>setFilters(f=>({...f,category:v}))}>{v}{v===filters.category&&<Check size={14}/>}</button>)}</div>{loading?<p>Loading catalogue…</p>:error?<p>Could not load catalogue: {error}</p>:<ProductGrid list={list} {...{openProduct,addToCart,toggleWish,wishlist}}/>}{!loading&&!error&&!list.length&&<div className="empty"><Search size={35}/><h3>No styles found</h3><p>Try another category or search.</p></div>}</div></main>}

function ProductGrid({list,openProduct,addToCart,toggleWish,wishlist}){return <div className="product-grid">{list.map(p=><ProductCard key={p.id} p={p} openProduct={openProduct} addToCart={addToCart} toggleWish={toggleWish} wish={wishlist.includes(p.id)}/>)}</div>}
function ProductCard({p,openProduct,addToCart,toggleWish,wish}){const price=p.salePrice||p.price;return <article className="product-card"><div className="product-media" onClick={()=>openProduct(p)}><img src={p.images[0]} alt={p.name} loading="lazy"/>{p.salePrice&&<span className="sale">SALE</span>}<button className={`heart ${wish?"active":""}`} onClick={e=>{e.stopPropagation();toggleWish(p)}}><Heart size={18} fill={wish?"currentColor":"none"}/></button><button className="quick" onClick={e=>{e.stopPropagation();openProduct(p)}}>QUICK VIEW</button></div><div className="product-info"><div className="product-top"><h3 onClick={()=>openProduct(p)}>{p.name}</h3><div className="price">{money(price)} {p.salePrice&&<del>{money(p.price)}</del>}</div></div><p>{p.desc}</p>{p.sizes.length>0&&<div className="sizes"><span>Sizes</span>{p.sizes.map(s=><i key={s}>{s}</i>)}</div>}<button className="add" onClick={()=>addToCart(p)}><ShoppingBag size={16}/> ADD TO CART</button></div></article>}

function Product({p,addToCart,toggleWish,wish,whatsapp}){const [size,setSize]=useState(p.sizes[1]||p.sizes[0]||"M");const [qty,setQty]=useState(1);const price=p.salePrice||p.price;return <main className="product-page"><div className="container"><div className="breadcrumbs">Home / {p.category} / {p.name}</div><div className="product-detail"><div className="gallery"><div className="gallery-main"><img src={p.images[0]} alt={p.name}/>{p.salePrice&&<span className="sale">SALE</span>}</div></div><div className="detail-copy"><div className="detail-kicker">{p.category} · {p.type}</div><h1>{p.name}</h1><div className="detail-price">{money(price)} {p.salePrice&&<del>{money(p.price)}</del>}</div><p className="lead">{p.desc}</p><div className="cod"><Check size={17}/><div><b>Cash on Delivery Available</b><span>Nationwide delivery · 2–5 working days</span></div></div><div className="selector"><label>Colour</label><div className="pills">{(p.colors.length?p.colors:["As shown"]).map(c=><button key={c}>{c}</button>)}</div></div><div className="selector"><label>Size</label><div className="pills">{(p.sizes.length?p.sizes:["M"]).map(s=><button className={s===size?"active":""} key={s} onClick={()=>setSize(s)}>{s}</button>)}</div></div><div className="buy-row"><div className="qty"><button onClick={()=>setQty(Math.max(1,qty-1))}><Minus size={15}/></button><span>{qty}</span><button onClick={()=>setQty(qty+1)}><Plus size={15}/></button></div><button className="btn primary grow" onClick={()=>{for(let i=0;i<qty;i++)addToCart(p,size)}}><ShoppingBag size={17}/> ADD TO CART</button><button className={`heart large ${wish?"active":""}`} onClick={()=>toggleWish(p)}><Heart size={19} fill={wish?"currentColor":"none"}/></button></div><button className="btn buy" onClick={()=>whatsapp(p)}>BUY NOW <ArrowRight size={17}/></button><div className="accordions"><details open><summary>Product details <ChevronDown size={17}/></summary><p>{p.fabric}. Product information is managed from the Store Manager.</p></details></div></div></div></div></main>}

function Cart({cart,setCart,total,delivery,setPage,openProduct}){const update=(x,d)=>setCart(c=>c.map(i=>i.id===x.id&&i.size===x.size?{...i,qty:Math.max(1,i.qty+d)}:i));return <main><div className="container narrow"><div className="page-title"><span className="eyebrow">YOUR EDIT</span><h1>Shopping Bag</h1><p>{cart.length?`${cart.reduce((s,x)=>s+x.qty,0)} item(s) ready for checkout.`:"Your bag is currently empty."}</p></div>{!cart.length?<div className="empty"><ShoppingBag size={40}/><h3>Nothing here yet</h3><button className="btn primary" onClick={()=>setPage("shop")}>SHOP THE COLLECTION</button></div>:<div className="cart-layout"><div className="cart-items">{cart.map(x=><div className="cart-item" key={`${x.id}-${x.size}`}><img src={x.images[0]} alt={x.name} onClick={()=>openProduct(x)}/><div><h3>{x.name}</h3><span>Size {x.size}</span><b>{money(x.salePrice||x.price)}</b><button className="remove" onClick={()=>setCart(c=>c.filter(i=>!(i.id===x.id&&i.size===x.size)))}>Remove</button></div><div className="qty"><button onClick={()=>update(x,-1)}><Minus size={14}/></button><span>{x.qty}</span><button onClick={()=>update(x,1)}><Plus size={14}/></button></div></div>)}</div><aside className="summary"><h3>Order Summary</h3><div><span>Subtotal</span><b>{money(total)}</b></div><div><span>Delivery</span><b>{delivery?money(delivery):"FREE"}</b></div><hr/><div className="total"><span>Total</span><b>{money(total+delivery)}</b></div><button className="btn primary full" onClick={()=>window.open(`https://wa.me/${WA_NUMBER}?text=${encodeURIComponent("Assalam o Alaikum! I would like to place an order from my cart. Please contact me to confirm.")}`,"_blank")}>ORDER ON WHATSAPP <MessageCircle size={17}/></button></aside></div>}</div></main>}

function Footer(){return <footer><div className="container footer-bottom"><span>© 2026 Noor & Co. All rights reserved.</span><span>Live catalogue · PKR · COD</span></div></footer>}
function FloatWA(){return <a className="wa-float" href={`https://wa.me/${WA_NUMBER}`} target="_blank" rel="noreferrer"><MessageCircle size={20}/><span>Order on WhatsApp</span></a>}
createRoot(document.getElementById("root")).render(<App/>);
